15 i18n 적용하기
TaskWeaver/frontend_app pull request #63
Opened 2024-03-07 22:11 UTC by brownglasses

## 요약

- [add] 현재 구성된 페이지에 i18n 을 적용하였습니다. 

터미널에 ```dart run build_runner build -d``` 을 입력하시면 i18n dart 파일을 생성하실 수 있습니다.

2024-03-10 09:31 UTC, jjoonleo approved these changes
수고하셨습니다.

2024-03-10 09:34 UTC, jjoonleo requested changes
웹 빌드 링크로 들어가 보았는데 화면이 나오지 않습니다. 확인 부탁드려요

2024-03-10 11:38 UTC, brownglasses commented
확인했습니다. 빠른 시간 안에 수정하겠습니다

2024-03-10 11:45 UTC, jjoonleo commented
그리고 한 가지 문제점이 더 있는 것 같습니다. 이렇게 되면 context가 있어야 텍스트를 얻어올 수 있어서 이렇게 되면 외부 class나 enum 같이 위젯 트리에서 벗어나 있는 곳에서는 사용하지 못한다는 문제가 있습니다. 이 점을 어떻게 해결하면 좋을까요?

2024-03-11 01:50 UTC, brownglasses commented
riverpod 을 통해 Transition 객체를 전역변수처럼 사용하는 것은 어떨까요?

2024-03-20 03:00 UTC, jjoonleo approved these changes
감사합니다 수고하셨습니다

2024-03-23 07:23 UTC, merged